
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: item-management-service
          uri:  lb://item-management-service
          predicates:
            - Path=/items/**
          filters:
            - name: JwtAuthFilter
              args:
                requiredRole: USER


        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - name: JwtAuthFilter
              args:
                requiredRole: ADMIN

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost