server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: authentication-service

#  cloud:
#    discovery:
#      client:
#        simple:
#          instances:
#            item-management-service:
#              - uri: http://item-management-service
#                port: ${server.port}
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
